### ISSUE TITLE
Bad gateway and no logs with minimal traefik setup

### ISSUE THREAD

**Issue by hood** [distribution/distribution-library-image#157]
Hi, with the following super minimal `docker-compose.yaml` setup, with the service getting exposed through Traefik, hitting the server via http returns me a 502 bad gateway error, and I’m getting no error logs in `registry`’s dedicated container. Any ideas why?

```yaml
version: '3.9'

services:
  myregistry:
    image: registry:2
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./data:/data
    restart: always
    ports:
      - 5000:5000
    networks:
      - proxy
      - default
    labels:
      traefik.enable: true
      traefik.docker.network: proxy
      traefik.http.routers.docker-registry-secure.entrypoints: websecure
      traefik.http.routers.docker-registry-secure.rule: Host(`myregistry.mydomain.tld`)
      traefik.http.services.docker-registry-secure.loadbalancer.server.port: 5000

networks:
  proxy:
    external: true
```
