### ISSUE TITLE
JWT validation problem on 3.0.0-rc.1 (kid format mismatch)

### ISSUE THREAD

**Issue by ericwyles** [distribution/distribution-library-image#179]
Hi, I'm testing 3.0.0-rc.1 using keycloak 26.0.5 as the auth server.

I am downloading the jwks keys from keycloak's openid-connect/certs endpoint: https://sso.uds.dev/realms/uds/protocol/openid-connect/certs and configuring registry to use that file for the `REGISTRY_AUTH_TOKEN_JWKS` in my docker compose yaml below:

```yaml
version: '3.8'

services:
  registry:
    image: registry:3.0.0-rc.1
    container_name: docker-registry
    ports:
      - "5001:5000"
    environment:
      REGISTRY_AUTH: token
      REGISTRY_AUTH_TOKEN_REALM: https://sso.uds.dev/realms/uds/protocol/docker-v2/auth
      REGISTRY_AUTH_TOKEN_SERVICE: docker-registry
      REGISTRY_AUTH_TOKEN_ISSUER: https://sso.uds.dev/realms/uds
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /etc/certs/keycloak.pem
      REGISTRY_AUTH_TOKEN_JWKS: /etc/jwks/jwks_original.json
      OTEL_TRACES_EXPORTER: none
    volumes:
      - ./data:/var/lib/registry
      - ./jwks:/etc/jwks
      - ./certs:/etc/certs
    restart: unless-stopped
```

With this configuration, I'm unable to perform `docker login` because there seems to be a problem resolving the token by kid.

The following error is printed in the registry log when I authenticate

`time="2024-12-12T18:40:32.10842518Z" level=info msg="failed to verify token: token signed by untrusted key with ID: \"24KL:52WX:HWNC:R2YW:I4TZ:T6UR:TKBS:TRGT:JCI6:NPHB:QTZW:7KCB\"`

The JWT is actually signed by the correct key and is valid, but it registry can't look it up to validate it.

If I modify the jwks file so the format of the `kid` field matches the expected then it works. An example modification is below:

Original certs file from keycloak:
```json
    {
      "kid": "1xS-6tc9mijrFkcnmfqRmoMpxNNIkea84YTzb6hBgeE",
      "kty": "RSA",
      "alg": "RS256",
      "use": "sig",
      "n": "REPLACED_FOR_BREVITY",
      "e": "AQAB",
      "x5c": [
        "REPLACED_FOR_BREVITY"
      ],
      "x5t": "REPLACED_FOR_BREVITY",
      "x5t#S256": "REPLACED_FOR_BREVITY"
    }
```

Modified certs file to match the kid format that works with registry:
```json
    {
      "kid": "24KL:52WX:HWNC:R2YW:I4TZ:T6UR:TKBS:TRGT:JCI6:NPHB:QTZW:7KCB",
      "kty": "RSA",
      "alg": "RS256",
      "use": "sig",
      "n": "REPLACED_FOR_BREVITY",
      "e": "AQAB",
      "x5c": [
        "REPLACED_FOR_BREVITY"
      ],
      "x5t": "REPLACED_FOR_BREVITY",
      "x5t#S256": "REPLACED_FOR_BREVITY"
    }
```

Another data point. On registry version 2.8.3, I don't need to pass `REGISTRY_AUTH_TOKEN_JWKS` -- Instead, it is able to validate my token using the key in the `REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE` pem file, which was created by exporting the contents `x5c[0]` field above and saving as a pem file. This works against the exact same installation as keycloak.

Any suggestions on how to get the tokens to validate in registry v3 without having to modify the jwks file? It seems like this should work directly with the file exported from the keycloak realm `/certs` endpoint but with the `kid` field mismatch I'm not sure if that's possible.

This `REGISTRY_AUTH_TOKEN_JWKS` seems new in v3 so wanted to report this since I'm running onto it.
